services:
  # Reverse proxy
  traefik:
    image: docker.io/library/traefik:v3.7.7
    command:
      - "--accesslog"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8080"
      - "--entrypoints.web.http.redirections.entrypoint.to=:443"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.middlewares=crowdsec@docker"
      - "--entrypoints.websecure.address=:8443"
      - "--entrypoints.websecure.http3"
      - "--entrypoints.websecure.http3.advertisedPort=443"
      - "--entrypoints.websecure.http.middlewares=crowdsec@docker"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare"
    environment:
      CF_DNS_API_TOKEN: ${TRAEFIK_CF_API_TOKEN}
      CF_ZONE_API_TOKEN: ${TRAEFIK_CF_API_TOKEN}
    volumes:
      - type: volume
        source: traefik-logs-vol
        target: /var/log/traefik
        volume:
          nocopy: false
      - type: volume
        source: traefik-acme-vol
        target: /acme
        volume:
          nocopy: false
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    ports:
      - "127.0.0.1:80:8080/tcp" # WARN: Accessible on localhost only (SSH tunnel)
      - "127.0.0.1:443:8443/tcp" # WARN: Accessible on localhost only (SSH tunnel)
      - "127.0.0.1:443:8443/udp" # WARN: Accessible on localhost only (SSH tunnel)
    networks:
      traefik-2-internet:
      traefik-2-wireguard:
      traefik-2-mist:
      traefik-2-graphix:
      wireguard-2-internal:
        ipv4_address: 172.16.13.1 # WARN: Makes ports above accessible over VPN
    restart: unless-stopped

  # VPN
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:15.3.0
    environment:
      WG_DEVICE: eth0
      INSECURE: true
      INIT_ENABLED: true
      INIT_USERNAME: ${VPN_GUI_USERNAME:-admin}
      INIT_PASSWORD: ${VPN_GUI_PASSWORD}
      INIT_HOST: ${VPN_DOMAIN}
      INIT_PORT: 51820
      INIT_DNS: ${VPN_DNS:-} # WARN: Remove empty DNS entry and add keepalive 25 via GUI
      INIT_IPV4_CIDR: "172.16.12.0/24"
      INIT_IPV6_CIDR: "2001:0DB8::/32"
      INIT_ALLOWED_IPS: "172.16.12.0/24,2001:0DB8::/32,172.16.13.0/24"
    volumes:
      - type: volume
        source: wireguard-conf-vol
        target: /etc/wireguard
        volume:
          nocopy: false
      - type: bind
        source: /lib/modules
        target: /lib/modules
        read_only: true
    ports:
      - "51820:51820/udp"
    networks:
      wireguard-2-internet:
        driver_opts:
          com.docker.network.endpoint.ifname: eth0
      wireguard-2-internal:
        driver_opts:
          com.docker.network.endpoint.ifname: eth1
        ipv4_address: 172.16.13.253
      wireguard-multipath-2-wireguard:
        driver_opts:
          com.docker.network.endpoint.ifname: eth2
      traefik-2-wireguard:
        driver_opts:
          com.docker.network.endpoint.ifname: eth3
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK_PREFIX}_traefik-2-wireguard"
      - "traefik.http.routers.wireguard.rule=Host(`${VPN_DOMAIN}`)"
      - "traefik.http.routers.wireguard.entrypoints=websecure"
      - "traefik.http.routers.wireguard.tls=true"
      - "traefik.http.routers.wireguard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wireguard.service=wireguard"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
    restart: unless-stopped

  wireguard-multipath:
    image: ghcr.io/blokadainfo/wireguard-multipath:v0.0.7
    command: ["server"]
    environment:
      WGMP_SERVER_WIREGUARD_ADDR: "wireguard:51820"
    ports:
      - "59501:59501/udp"
    networks:
      wireguard-multipath-2-internet:
      wireguard-multipath-2-wireguard:
    restart: unless-stopped

  iperf:
    image: docker.io/networkstatic/iperf3:latest
    command: ["-s", "-p", "5201"]
    # ports:
    #   - "5201:5201/tcp"
    #   - "5201:5201/udp"
    networks:
      wireguard-2-internal:
        ipv4_address: 172.16.13.3
    restart: unless-stopped

  # BelaUI Remote
  belaui-remote:
    image: docker.io/library/caddy:2.11.4
    environment:
      BELAUI_REMOTE_DOMAIN: ${BELAUI_REMOTE_DOMAIN}
    volumes:
      - type: bind
        source: ./config/belaui.Caddyfile
        target: /etc/caddy/Caddyfile
        read_only: true
    network_mode: service:wireguard # Required to reverse proxy requests to internal VPN network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK_PREFIX}_traefik-2-wireguard" # WARN: network_mode: service:wireguard
      - "traefik.http.routers.belaui-remote.rule=Host(`*.${BELAUI_REMOTE_DOMAIN}`)" # WARN: Wildcard subdomain
      - "traefik.http.routers.belaui-remote.entrypoints=websecure"
      - "traefik.http.routers.belaui-remote.tls=true"
      - "traefik.http.routers.belaui-remote.tls.certresolver=letsencrypt"
      - "traefik.http.routers.belaui-remote.service=belaui-remote"
      - "traefik.http.services.belaui-remote.loadbalancer.server.port=80"
    restart: unless-stopped

  # Restreamer
  mist:
    image: docker.io/ddvtech/mistserver:3.9.2
    command: ["-c", "/var/mist/config.json"]
    shm_size: 8gb
    environment:
      DOMAIN: ${MIST_DOMAIN}
    ports:
      # - "1934:1934/tcp" # RTMP IN
      - "1935:1935/tcp" # RTMP OUT
      - "8889:8889/udp" # SRT IN
      - "9000:9000/udp" # SRT OUT
    networks:
      - mist-2-internet
      - mist-2-bbox-receiver
      - traefik-2-mist
      - overlayer-2-mist
      - streamecho-2-mist
      - streamecho-locked-2-mist
    volumes:
      - type: volume
        source: mist-data-vol
        target: /var/mist
        volume:
          nocopy: false
      - type: volume
        source: mist-video-vol
        target: /video
        volume:
          nocopy: false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK_PREFIX}_traefik-2-mist"
      - "traefik.http.routers.mist-ui.rule=Host(`${MIST_DOMAIN}`)"
      - "traefik.http.routers.mist-ui.entrypoints=websecure"
      - "traefik.http.routers.mist-ui.tls=true"
      - "traefik.http.routers.mist-ui.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mist-ui.service=mist-ui"
      - "traefik.http.services.mist-ui.loadbalancer.server.port=4242"
      # TODO
      # - "traefik.http.routers.mist-preview.rule=Host(`${MIST_PREVIEW_DOMAIN}`)"
      # - "traefik.http.routers.mist-preview.entrypoints=websecure"
      # - "traefik.http.routers.mist-preview.tls=true"
      # - "traefik.http.routers.mist-preview.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.mist-preview.service=mist-preview"
      # - "traefik.http.services.mist-preview.loadbalancer.server.port=8080"
    restart: unless-stopped
    healthcheck:
      disable: true # TODO

  bbox-receiver:
    image: docker.io/datagutt/belabox-receiver:3.5.0
    ports:
      - "5000:5000/udp" # SRTLA IN
      # - "8282:8282/udp" # SRT OUT - Not needed as we pull the stream in Mist (docker internal network)
      # - "8181:8181/tcp" # Stats - Not needed (yet)
      # - "3000:3000/tcp" # Stats (Legacy) - Not needed
    volumes:
      - type: bind
        source: ./config/bbox-receiver.json
        target: /app/config.json
        read_only: true
    networks:
      - bbox-receiver-2-internet
      - mist-2-bbox-receiver
    restart: unless-stopped

  overlayer:
    image: ghcr.io/blokadainfo/overlayer:v1.0.0
    environment:
      OVERLAY_LOGO_PATH: "/logo.svg"
      OVERLAY_LOGO_HEIGHT: 128
      OVERLAY_LOGO_WIDTH: 128
      OVERLAY_LOGO_ALPHA: 1
      STREAMS_0_SRC: ${OVERLAYER_STREAMS_0_SRC}
      STREAMS_0_DST: ${OVERLAYER_STREAMS_0_DST}
      STREAMS_1_SRC: ${OVERLAYER_STREAMS_1_SRC}
      STREAMS_1_DST: ${OVERLAYER_STREAMS_1_DST}
      STREAMS_2_SRC: ${OVERLAYER_STREAMS_2_SRC}
      STREAMS_2_DST: ${OVERLAYER_STREAMS_2_DST}
      STREAMS_3_SRC: ${OVERLAYER_STREAMS_3_SRC}
      STREAMS_3_DST: ${OVERLAYER_STREAMS_3_DST}
      STREAMS_4_SRC: ${OVERLAYER_STREAMS_4_SRC}
      STREAMS_4_DST: ${OVERLAYER_STREAMS_4_DST}
    volumes:
      - type: bind
        source: ./logo.svg
        target: /logo.svg
        read_only: true
    networks:
      - overlayer-2-mist
    restart: unless-stopped

  # Graphix
  graphix:
    image: ghcr.io/djordje-mancic/graphix:0.0.1
    volumes:
      - type: bind
        source: ${GRAPHIX_GRAPHICS_PATH}
        target: /app/graphics
        read_only: true
    networks:
      - traefik-2-graphix
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK_PREFIX}_traefik-2-graphix"
      - "traefik.http.routers.graphix.rule=Host(`${GRAPHIX_DOMAIN}`)"
      - "traefik.http.routers.graphix.entrypoints=websecure"
      - "traefik.http.routers.graphix.tls=true"
      - "traefik.http.routers.graphix.tls.certresolver=letsencrypt"
      - "traefik.http.routers.graphix.service=graphix"
      - "traefik.http.services.graphix.loadbalancer.server.port=3000"
    restart: unless-stopped

  # VoIP
  mumble:
    image: docker.io/mumblevoip/mumble-server:v1.5.901
    environment:
      MUMBLE_SUPERUSER_NAME: admin
      MUMBLE_SUPERUSER_PASSWORD: ${MUMBLE_ADMIN_PASSWORD}
      MUMBLE_CONFIG_SERVER_PASSWORD: ${MUMBLE_USER_PASSWORD}
    volumes:
      - type: volume
        source: mumble-data-vol
        target: /data
        volume:
          nocopy: false
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    networks:
      mumble-2-internet:
      streamecho-2-mumble:
      streamecho-locked-2-mumble:
      streamecho-audiocircuit-2-mumble:
      wireguard-2-internal:
        ipv4_address: 172.16.13.2
    restart: unless-stopped

  streamecho:
    image: ghcr.io/blokadainfo/streamecho:v0.0.4
    environment:
      MUMBLE_ADDRESS: "mumble:64738"
      MUMBLE_USERNAME: "@LEGACY.PROGRAM.LIVE.BOT"
      MUMBLE_PASSWORD: ${MUMBLE_USER_PASSWORD}
      MUMBLE_CHANNEL: ${STREAMECHO_MUMBLE_CHANNEL:-}
      SOURCE: ${STREAMECHO_STREAM_URL}
    networks:
      - streamecho-2-mist
      - streamecho-2-mumble
    restart: unless-stopped

  streamecho-locked:
    image: ghcr.io/blokadainfo/streamecho:v0.0.4
    environment:
      MUMBLE_ADDRESS: "mumble:64738"
      MUMBLE_USERNAME: "_ne_pomeraj_me_@PROGRAM.LIVE.BOT"
      MUMBLE_PASSWORD: ${MUMBLE_USER_PASSWORD}
      MUMBLE_CHANNEL: ${STREAMECHO_LOCKED_MUMBLE_CHANNEL:-}
      MUMBLE_CHANNEL_LOCK: "true"
      SOURCE: ${STREAMECHO_STREAM_URL}
    networks:
      - streamecho-locked-2-mist
      - streamecho-locked-2-mumble
    restart: unless-stopped

  streamecho-audiocircuit:
    image: ghcr.io/blokadainfo/streamecho:v0.0.4
    environment:
      MUMBLE_ADDRESS: "mumble:64738"
      MUMBLE_USERNAME: "_ne_pomeraj_me_@TEST.AUDIO.BOT"
      MUMBLE_PASSWORD: ${MUMBLE_USER_PASSWORD}
      MUMBLE_CHANNEL: ${STREAMECHO_AUDIO_CIRCUIT_MUMBLE_CHANNEL:-}
      MUMBLE_CHANNEL_LOCK: "true"
      SOURCE: "/audiocircuit.m4a"
      DELAY_SECONDS: 0
    volumes:
      - type: bind
        source: ./audiocircuit.m4a
        target: /audiocircuit.m4a
        read_only: true
    networks:
      - streamecho-audiocircuit-2-mumble
    restart: unless-stopped

networks:
  traefik-2-internet:
    internal: false
  traefik-2-wireguard:
    internal: true
  traefik-2-mist:
    internal: true
  traefik-2-graphix:
    internal: true
  wireguard-2-internet:
    internal: false
  wireguard-2-internal:
    internal: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.13.0/24"
          gateway: "172.16.13.254"
  wireguard-multipath-2-internet:
    internal: false
  wireguard-multipath-2-wireguard:
    internal: true
  mist-2-internet:
    internal: false
  mist-2-bbox-receiver:
    internal: true
  bbox-receiver-2-internet:
    internal: false
  overlayer-2-mist:
    internal: true
  mumble-2-internet:
    internal: false
  streamecho-2-mist:
    internal: true
  streamecho-2-mumble:
    internal: true
  streamecho-locked-2-mist:
    internal: true
  streamecho-locked-2-mumble:
    internal: true
  streamecho-audiocircuit-2-mumble:
    internal: true

volumes:
  traefik-logs-vol:
  traefik-acme-vol:
  wireguard-conf-vol:
  mist-data-vol:
  mist-video-vol:
  mumble-data-vol:
