services:
  # Reverse proxy
  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:v1.6.11
    environment:
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
      CUSTOM_HOSTNAME: crowdsec
      BOUNCER_KEY_TRAEFIK: ${BOUNCER_KEY_TRAEFIK}
    volumes:
      - type: volume
        source: traefik-logs-vol
        target: /var/log/traefik
        volume:
          nocopy: false
      - type: volume
        source: crowdsec-db-vol
        target: /var/lib/crowdsec/data
        volume:
          nocopy: false
      - type: volume
        source: crowdsec-conf-vol
        target: /etc/crowdsec
        volume:
          nocopy: false
      - type: bind
        source: ./acquis.yaml
        target: /etc/crowdsec/acquis.yaml
        read_only: true
    networks:
      - traefik-2-crowdsec
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider --quiet --tries=1 --timeout=5 http://localhost:8080/health > /dev/null 2>&1 || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  traefik:
    image: docker.io/library/traefik:v3.6.6
    command:
      - "--accesslog"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8080"
      - "--entrypoints.web.http.redirections.entrypoint.to=:443"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.middlewares=crowdsec@docker"
      - "--entrypoints.websecure.address=:8443"
      - "--entrypoints.websecure.http3"
      - "--entrypoints.websecure.http3.advertisedPort=443"
      - "--entrypoints.websecure.http.middlewares=crowdsec@docker"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--experimental.plugins.bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      - "--experimental.plugins.bouncer.version=v1.4.6"
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp"
    volumes:
      - type: volume
        source: traefik-logs-vol
        target: /var/log/traefik
        volume:
          nocopy: false
      - type: volume
        source: traefik-acme-vol
        target: /acme
        volume:
          nocopy: false
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - traefik-2-crowdsec
      - traefik-2-whoami
      - traefik-2-mist
      - traefik-2-wireguard
    restart: unless-stopped
    depends_on:
      crowdsec:
        condition: service_healthy
        restart: true

  whoami:
    image: docker.io/traefik/whoami:v1.11
    command:
      - "--port=8080"
      - "--name=whoami"
    networks:
      - traefik-2-whoami
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK_PREFIX}_traefik-2-whoami"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecmode=stream"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapikey=${BOUNCER_KEY_TRAEFIK}"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecappsecenabled=true"
      - "traefik.http.middlewares.authelia.forwardAuth.address=https://${AUTHELIA_DOMAIN}/api/authz/forward-auth"
      - "traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name"

  # Mist
  mist:
    image: docker.io/ddvtech/mistserver:3.9.2
    command:
      - "-c"
      - "/var/mist/config.json"
    shm_size: 8gb
    environment:
      DOMAIN: ${MIST_DOMAIN}
    ports:
      - "1935:1935/tcp" # RTMP IN/OUT
      - "8889:8889/udp" # SRT IN
      - "9000:9000/udp" # SRT OUT
    networks:
      - mist-2-bbox-receiver
      - traefik-2-mist
      - overlayer-2-mist
      - streamecho-2-mist
    volumes:
      - type: volume
        source: mist-data-vol
        target: /var/mist
        volume:
          nocopy: false
      - type: volume
        source: mist-video-vol
        target: /video
        volume:
          nocopy: false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK_PREFIX}_traefik-2-mist"
      - "traefik.http.routers.mist-ui.rule=Host(`${MIST_DOMAIN}`)"
      - "traefik.http.routers.mist-ui.middlewares=authelia@docker"
      - "traefik.http.routers.mist-ui.entrypoints=websecure"
      - "traefik.http.routers.mist-ui.tls=true"
      - "traefik.http.routers.mist-ui.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mist-ui.service=mist-ui"
      - "traefik.http.services.mist-ui.loadbalancer.server.port=4242"
      # TODO
      # - "traefik.http.routers.mist-preview.rule=Host(`${MIST_PREVIEW_DOMAIN}`)"
      # - "traefik.http.routers.mist-preview.entrypoints=websecure"
      # - "traefik.http.routers.mist-preview.tls=true"
      # - "traefik.http.routers.mist-preview.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.mist-preview.service=mist-preview"
      # - "traefik.http.services.mist-preview.loadbalancer.server.port=8080"
    restart: unless-stopped
    healthcheck:
      disable: true # TODO

  # BBox Receiver
  bbox-receiver:
    image: docker.io/datagutt/belabox-receiver:2.9.0
    ports:
      - "5000:5000/udp" # SRTLA
      # - "8282:8282/udp" # SRT OUT - Not needed as we pull the stream in Mist (docker internal network)
      # - "8181:8181/tcp" # Stats - Not needed (yet)
      # - "3000:3000/tcp" # Stats (Legacy) - Not needed
    volumes:
      - type: bind
        source: ./config/bbox-receiver.json
        target: /app/config.json
        read_only: true
    networks:
      - mist-2-bbox-receiver
    restart: unless-stopped

  # Overlayer
  overlayer:
    image: ghcr.io/blokadainfo/overlayer:v1.0.0
    environment:
      OVERLAY_LOGO_PATH: "/logo.svg"
      OVERLAY_LOGO_HEIGHT: 128
      OVERLAY_LOGO_WIDTH: 128
      OVERLAY_LOGO_ALPHA: 1
      STREAMS_0_SRC: ${OVERLAYER_STREAMS_0_SRC}
      STREAMS_0_DST: ${OVERLAYER_STREAMS_0_DST}
      STREAMS_1_SRC: ${OVERLAYER_STREAMS_1_SRC}
      STREAMS_1_DST: ${OVERLAYER_STREAMS_1_DST}
      STREAMS_2_SRC: ${OVERLAYER_STREAMS_2_SRC}
      STREAMS_2_DST: ${OVERLAYER_STREAMS_2_DST}
      STREAMS_3_SRC: ${OVERLAYER_STREAMS_3_SRC}
      STREAMS_3_DST: ${OVERLAYER_STREAMS_3_DST}
    volumes:
      - type: bind
        source: ./logo.svg
        target: /logo.svg
        read_only: true
    networks:
      - overlayer-2-mist
    restart: unless-stopped

  # Mumble
  mumble:
    image: docker.io/mumblevoip/mumble-server:v1.5.857
    environment:
      MUMBLE_SUPERUSER_NAME: admin
      MUMBLE_SUPERUSER_PASSWORD: ${MUMBLE_ADMIN_PASSWORD}
      MUMBLE_CONFIG_SERVER_PASSWORD: ${MUMBLE_USER_PASSWORD}
    volumes:
      - type: volume
        source: mumble-data-vol
        target: /data
        volume:
          nocopy: false
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    networks:
      - streamecho-2-mumble
    restart: unless-stopped

  # StreamEcho
  streamecho:
    image: ghcr.io/blokadainfo/streamecho:v0.0.1
    environment:
      MUMBLE_ADDRESS: ${STREAMECHO_MUMBLE_ADDRESS} # TODO: Why mumble internal net doesn't work?
      MUMBLE_USERNAME: "@PROGRAM.LIVE"
      MUMBLE_PASSWORD: ${MUMBLE_USER_PASSWORD}
      STREAM_URL: ${STREAMECHO_STREAM_URL}
    networks:
      - streamecho-2-mist
      - streamecho-2-mumble
    restart: unless-stopped

networks:
  traefik-2-crowdsec:
  traefik-2-whoami:
  traefik-2-mist:
  mist-2-bbox-receiver:
  overlayer-2-mist:
  streamecho-2-mist:
  streamecho-2-mumble:

volumes:
  crowdsec-db-vol:
  crowdsec-conf-vol:
  traefik-logs-vol:
  traefik-acme-vol:
  mist-data-vol:
  mist-video-vol:
  mumble-data-vol:
